### ISSUE TITLE
Unusable without numpad

### ISSUE THREAD

**Issue by PweSol** [PureDark/VRisingDLSSMod#3]
Hello, I have a tkl keyboard, which means I can't enable this mod in game. Is there a way how to configure the keybinds? If there isn't, would it be possible to add some kind of configuration please? Or maybe just add an alternative default keybinds like fn+shift+1/2/3, or something like that.

**Comment by PweSol** [comment]
Turns out I'm dumb and haven't noticed you can rebind trough the config.

**Comment by Erroneuz** [comment]
Some hints to what config file and what should be changed, to change the hotkey.

Thanks.
