### ISSUE TITLE
Gloomrot Update Support?

### ISSUE THREAD

**Issue by blaesink** [PureDark/VRisingDLSSMod#4]
Maybe I've done this wrong (new to the game and modding it), but it seems that Gloomrot (may have) broken compatibility with this mod. Any help is appreciated!

**Comment by ilkekaratas** [comment]
Yes! I am looking for this too!

**Comment by Wyll3R** [comment]
Please update. Very nice mod!

**Comment by PureDark** [comment]
I made this mod for practice, I don't even play V Rising.
That's why I open sourced it, anyone with enough coding in unity experience can update it.

**Comment by blaesink** [comment]
> I made this mod for practice, I don't even play V Rising. That's why I open sourced it, anyone with enough coding in unity experience can update it.

Fair enough 😅. If I get the time I'll give it a shot, I'm not a C# dev but if it's for a good cause I'll take the plunge.
